### ISSUE TITLE
Update to iltorb 2.x

### ISSUE THREAD

**Issue by edmorley** [erwinmombay/brotli-size#1]
Hi!

`brotli-size` currently has a dependency on [iltorb](https://github.com/MayhemYDG/iltorb) `^1.0.9`, however I was hoping to be able to make use of a fix that's only landed in 2.0.4 ([changelog](https://github.com/MayhemYDG/iltorb/blob/master/CHANGELOG.md)).

Could the dep be updated?

Many thanks :-)

P.S.: For several projects I use the [Renovate](https://renovateapp.com/) bot to keep deps up to date - I'd highly recommend it longer term to reduce effort.

**Comment by erwinmombay** [comment]
@edmorley thanks for the issue! will update. also i appreciate you mentioning renovate, I'll try to set it up.

**Comment by erwinmombay** [comment]
Fixed by https://github.com/erwinmombay/brotli-size/pull/2

**Comment by erwinmombay** [comment]
@edmorley i've publish 0.0.2 version of brotli-size. Thanks so much for the report 💯 and LMK if theres any issues

**Comment by edmorley** [comment]
Many thanks! :-)
