### ISSUE TITLE
v2.0.0 not published to NPM

### ISSUE THREAD

**Issue by bartveneman** [erwinmombay/brotli-size#14]
The 'versions' tab on https://www.npmjs.com/package/brotli-size doesn't show the v2 tag. It would be convinient to be able to use NPM instead of having to install from GitHub. 😄

**Comment by erwinmombay** [comment]
@bartveneman yeah this was my bad as i made a mistake publishing and screwed up by unpublishing it. i did re-release it as > 3.x.x. are you able to use 3?

**Comment by bartveneman** [comment]
Oh, then I must have misread the version instructions. If 3.x.x also works for Node 8, I’ll be fine. 😀

**Comment by kristoferbaxter** [comment]
3.x works with node ≥ 10.16

1.x works with node < 10.16

If you're on node 8, you'll want to use ^1.0 or pin to a 1.0 release.

**Comment by bartveneman** [comment]
Thanks for the explanation!
