### ISSUE TITLE
TypeError: zlib_1.brotliCompressSync is not a function

### ISSUE THREAD

**Issue by alexeychikk** [erwinmombay/brotli-size#19]
Example from README not working:
```js
const brotliSize = require("brotli-size");
const brotliCodeSize = brotliSize.sync(code);
```
The following error occurs:
```
(node:18015) UnhandledPromiseRejectionWarning: TypeError: zlib_1.brotliCompressSync is not a function
```

**Comment by alexeychikk** [comment]
That's because `zlib` is not in dependencies. Seems like the project is abandoned.

**Comment by kristoferbaxter** [comment]
Are you using a recent version of node? This method is available in the stable LTS release.

from `package.json`, node `10.16` is the minimum supported version:
```json
"engines": {
  "node": ">= 10.16.0"
}
```

**Comment by dkmin** [comment]
it works node v14.7.x in my case.
