### ISSUE TITLE
Audit fails due to iltorb > node-gyp > tar

### ISSUE THREAD

**Issue by ghost** [erwinmombay/brotli-size#8]
Any chance `iltorb` dep could be upgraded? It's currently at `^2.0.5`, which causes the audit to fail. Although it should match up to minor, looking at `yarn.lock` that doesn't seem to be the case. Upgrading to `2.4.2` should fix the error.

To give more context, I am getting it via `bundlesize`

<img width="654" alt="Screen Shot 2019-04-12 at 2 01 49 PM" src="https://user-images.githubusercontent.com/32908329/56056932-9964ae80-5d2b-11e9-9f79-e3d6c180a067.png">

**Comment by erwinmombay** [comment]
@alexnez96 thanks so much for the issue and my apologies for the late update.
I've updated the dependency to `iltorb` to `2.4.3` and bumped up the version to `brotli-size` to `0.1.0` and published it.

https://github.com/erwinmombay/brotli-size/pull/9
https://github.com/erwinmombay/brotli-size/pull/10

**Comment by ghost** [comment]
Thanks @erwinmombay!
